export const MUTATIONS_SET_COMMENT = "MUTATIONS_SET_COMMENT";
export const MUTATIONS_ADD_COMMENT = "MUTATIONS_ADD_COMMENT";
export const MUTATIONS_APPEND_COMMENT = "MUTATIONS_APPEND_COMMENT";

export const ACTIONS_FETCH_COMMENTS = "ACTIONS_FETCH_COMMENTS";
export const ACTIONS_FETCH_NEXT_PAGE_COMMENTS =
  "ACTIONS_FETCH_NEXT_PAGE_COMMENTS";
export const ACTIONS_ADD_COMMENT = "ACTIONS_ADD_COMMENT";
export const ACTIONS_REPLY_COMMENT = "ACTIONS_REPLY_COMMENT";
