name: Update_murr_front_on_prod

on:
  push:
    branches: [ master ]

jobs:
  build_new_murr_front:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      
      - name: npm install stage
        run: npm i

      - name: npm run build stage
        run: npm run build
        
      - name: Copy dist to prod stand
        uses: horochx/deploy-via-scp@master
        with:
          local: dist
          remote: /home/murrengan_test/murr_back
          host: 35.228.83.205
          port: 22
          user: murrengan_test
          key: ${{ secrets.PRIVATE_KEY }}
      
      - name: Restart docker-compose on prod
        uses: appleboy/ssh-action@master
        with:
          host: 35.228.83.205
          username: murrengan_test
          key: ${{ secrets.PRIVATE_KEY }}
          port: 22
          script: |
           cd ~/murr_back
           docker-compose -f docker-compose-prod.yml down
           docker-compose -f docker-compose-prod.yml up --build -d
